/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.demo.vista;

import javax.swing.JButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jtpTables = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPasswords = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtUsers = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnSelectPassword = new javax.swing.JButton();
        btnSelectUsers = new javax.swing.JButton();
        btnSelectInfo = new javax.swing.JButton();
        jtpInputs = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmailPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPasswordPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNotePassword = new javax.swing.JTextField();
        btnSavePassword = new javax.swing.JButton();
        btnDeletePassword = new javax.swing.JButton();
        btnUpdatePassword = new javax.swing.JButton();
        btnCleanPassword = new javax.swing.JButton();
        txtIdPassword = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSearchPassword = new javax.swing.JTextField();
        btnSearchPassword = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSearchUser = new javax.swing.JTextField();
        btnSearchUser = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        btnNewUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 300));

        jPanel1.setBackground(new java.awt.Color(193, 151, 210));

        jPanel3.setBackground(new java.awt.Color(242, 206, 216));

        jPanel4.setBackground(new java.awt.Color(199, 179, 242));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(199, 179, 242));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, 28));

        jPanel11.setBackground(new java.awt.Color(199, 179, 242));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 690, 8));

        jPanel12.setBackground(new java.awt.Color(199, 179, 242));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 680, 13));

        jtpTables.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel5.setBackground(new java.awt.Color(242, 167, 187));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(254, 207, 220), new java.awt.Color(13, 13, 13)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(13, 13, 13));
        jScrollPane1.setForeground(new java.awt.Color(254, 207, 220));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtPasswords.setBackground(new java.awt.Color(13, 13, 13));
        jtPasswords.setForeground(new java.awt.Color(254, 207, 220));
        jtPasswords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Correo", "Descripcion."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPasswords.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jtPasswords.setShowGrid(false);
        jScrollPane1.setViewportView(jtPasswords);
        if (jtPasswords.getColumnModel().getColumnCount() > 0) {
            jtPasswords.getColumnModel().getColumn(0).setMinWidth(0);
            jtPasswords.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtPasswords.getColumnModel().getColumn(0).setMaxWidth(0);
            jtPasswords.getColumnModel().getColumn(1).setResizable(false);
            jtPasswords.getColumnModel().getColumn(1).setPreferredWidth(270);
            jtPasswords.getColumnModel().getColumn(2).setResizable(false);
            jtPasswords.getColumnModel().getColumn(2).setPreferredWidth(400);
        }

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 270));

        jtpTables.addTab("tab1", jPanel5);

        jPanel6.setBackground(new java.awt.Color(242, 167, 187));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(254, 207, 220), new java.awt.Color(13, 13, 13)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtUsers.setBackground(new java.awt.Color(13, 13, 13));
        jtUsers.setForeground(new java.awt.Color(254, 207, 220));
        jtUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtUsers);
        if (jtUsers.getColumnModel().getColumnCount() > 0) {
            jtUsers.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 270));

        jtpTables.addTab("tab2", jPanel6);

        jPanel7.setBackground(new java.awt.Color(242, 167, 187));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(254, 207, 220), new java.awt.Color(13, 13, 13)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informationGirl.png"))); // NOI18N
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 647, -1));

        jtpTables.addTab("tab3", jPanel7);

        jPanel4.add(jtpTables, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, 670, 320));

        btnSelectPassword.setBackground(new java.awt.Color(13, 13, 13));
        btnSelectPassword.setForeground(new java.awt.Color(254, 207, 220));
        btnSelectPassword.setText("<html> \nContraseñas.\n</html>");
        btnSelectPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPasswordActionPerformed(evt);
            }
        });
        jPanel4.add(btnSelectPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 152, 35));

        btnSelectUsers.setBackground(new java.awt.Color(13, 13, 13));
        btnSelectUsers.setForeground(new java.awt.Color(254, 207, 220));
        btnSelectUsers.setText("<html>\nUsuarios.\n</html>");
        jPanel4.add(btnSelectUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 152, 35));

        btnSelectInfo.setBackground(new java.awt.Color(13, 13, 13));
        btnSelectInfo.setForeground(new java.awt.Color(254, 207, 220));
        btnSelectInfo.setText("<html> Información. </html>");
        jPanel4.add(btnSelectInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 152, 35));

        jPanel8.setBackground(new java.awt.Color(242, 167, 187));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(254, 207, 220), new java.awt.Color(13, 13, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 13, 13));
        jLabel2.setText("Correo:");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        txtEmailPassword.setBackground(new java.awt.Color(13, 13, 13));
        txtEmailPassword.setForeground(new java.awt.Color(254, 207, 220));
        jPanel8.add(txtEmailPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 183, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 13, 13));
        jLabel3.setText("Contraseña:");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 62, -1, -1));

        txtPasswordPassword.setBackground(new java.awt.Color(13, 13, 13));
        txtPasswordPassword.setForeground(new java.awt.Color(254, 207, 220));
        jPanel8.add(txtPasswordPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 88, 191, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 13, 13));
        jLabel4.setText("Notas:");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 8, -1, -1));

        txtNotePassword.setBackground(new java.awt.Color(13, 13, 13));
        txtNotePassword.setForeground(new java.awt.Color(254, 207, 220));
        jPanel8.add(txtNotePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 30, 200, 80));

        btnSavePassword.setBackground(new java.awt.Color(242, 167, 187));
        btnSavePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jPanel8.add(btnSavePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 48, 48));

        btnDeletePassword.setBackground(new java.awt.Color(242, 167, 187));
        btnDeletePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jPanel8.add(btnDeletePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 48, 48));

        btnUpdatePassword.setBackground(new java.awt.Color(242, 167, 187));
        btnUpdatePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        jPanel8.add(btnUpdatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 48, 48));

        btnCleanPassword.setBackground(new java.awt.Color(242, 167, 187));
        btnCleanPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clean.png"))); // NOI18N
        jPanel8.add(btnCleanPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 48, 48));

        txtIdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPasswordActionPerformed(evt);
            }
        });
        jPanel8.add(txtIdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 8, 0, 0));

        jPanel13.setBackground(new java.awt.Color(231, 198, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(13, 13, 13));
        jLabel5.setText("Buscar contraseña:");

        txtSearchPassword.setBackground(new java.awt.Color(255, 214, 255));
        txtSearchPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchPassword.setForeground(new java.awt.Color(13, 13, 13));

        btnSearchPassword.setBackground(new java.awt.Color(255, 198, 255));
        btnSearchPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchPassword.setForeground(new java.awt.Color(13, 13, 13));
        btnSearchPassword.setText("Buscar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearchPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                    .addComponent(jLabel5))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 116, 500, 45));

        jtpInputs.addTab("tab1", jPanel8);

        jPanel9.setBackground(new java.awt.Color(242, 167, 187));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(254, 207, 220), new java.awt.Color(13, 13, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(231, 198, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(13, 13, 13));
        jLabel6.setText("Buscar usuario:");

        txtSearchUser.setBackground(new java.awt.Color(255, 214, 255));

        btnSearchUser.setBackground(new java.awt.Color(255, 198, 255));
        btnSearchUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchUser.setForeground(new java.awt.Color(13, 13, 13));
        btnSearchUser.setText("Buscar");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 116, 500, 45));

        jPanel16.setBackground(new java.awt.Color(231, 198, 255));

        btnNewUser.setBackground(new java.awt.Color(255, 198, 255));
        btnNewUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNewUser.setForeground(new java.awt.Color(13, 13, 13));
        btnNewUser.setText("Registrar Nuevo Usuario.");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setBackground(new java.awt.Color(255, 198, 255));
        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteUser.setForeground(new java.awt.Color(13, 13, 13));
        btnDeleteUser.setText("Eliminar Usuario.");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(btnNewUser)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteUser)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 370, 100));

        jtpInputs.addTab("tab2", jPanel9);

        jPanel10.setBackground(new java.awt.Color(242, 167, 187));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(254, 207, 220), new java.awt.Color(13, 13, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(13, 13, 13));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Información.");

        jTextArea1.setBackground(new java.awt.Color(231, 198, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(13, 13, 13));
        jTextArea1.setRows(5);
        jTextArea1.setText("           Aplicación realizada por Ruisu Eurimonio\n                                Versión actual: 1.0\n               Fecha de realizacion: En desarrollo.\n    Funcionalidad: Gestionar contraseñas personales\n            en una base de datos MySql de manera\n                               encriptada y segura.");
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpInputs.addTab("tab3", jPanel10);

        jPanel4.add(jtpInputs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -10, 520, 202));
        jtpInputs.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 730, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPasswordActionPerformed

    private void btnSelectPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPasswordActionPerformed

    }//GEN-LAST:event_btnSelectPasswordActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanPassword;
    private javax.swing.JButton btnDeletePassword;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton btnSavePassword;
    private javax.swing.JButton btnSearchPassword;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JButton btnSelectInfo;
    private javax.swing.JButton btnSelectPassword;
    private javax.swing.JButton btnSelectUsers;
    private javax.swing.JButton btnUpdatePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable jtPasswords;
    private javax.swing.JTable jtUsers;
    private javax.swing.JTabbedPane jtpInputs;
    private javax.swing.JTabbedPane jtpTables;
    private javax.swing.JTextField txtEmailPassword;
    private javax.swing.JTextField txtIdPassword;
    private javax.swing.JTextField txtNotePassword;
    private javax.swing.JTextField txtPasswordPassword;
    private javax.swing.JTextField txtSearchPassword;
    private javax.swing.JTextField txtSearchUser;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCleanPassword() {
        return btnCleanPassword;
    }

    public void setBtnCleanPassword(JButton btnCleanPassword) {
        this.btnCleanPassword = btnCleanPassword;
    }

    public JButton getBtnDeletePassword() {
        return btnDeletePassword;
    }

    public void setBtnDeletePassword(JButton btnDeletePassword) {
        this.btnDeletePassword = btnDeletePassword;
    }

    public JButton getBtnSavePassword() {
        return btnSavePassword;
    }

    public void setBtnSavePassword(JButton btnSavePassword) {
        this.btnSavePassword = btnSavePassword;
    }

    public JButton getBtnSearchPassword() {
        return btnSearchPassword;
    }

    public void setBtnSearchPassword(JButton btnSearchPassword) {
        this.btnSearchPassword = btnSearchPassword;
    }

    public JButton getBtnSelectConfig() {
        return btnSelectInfo;
    }

    public void setBtnSelectConfig(JButton btnSelectConfig) {
        this.btnSelectInfo = btnSelectConfig;
    }

    public JButton getBtnSelectPassword() {
        return btnSelectPassword;
    }

    public void setBtnSelectPassword(JButton btnSelectPassword) {
        this.btnSelectPassword = btnSelectPassword;
    }

    public JButton getBtnSelectUsers() {
        return btnSelectUsers;
    }

    public void setBtnSelectUsers(JButton btnSelectUsers) {
        this.btnSelectUsers = btnSelectUsers;
    }

    public JButton getBtnUpdatePassword() {
        return btnUpdatePassword;
    }

    public void setBtnUpdatePassword(JButton btnUpdatePassword) {
        this.btnUpdatePassword = btnUpdatePassword;
    }

    public JTabbedPane getJtpInputs() {
        return jtpInputs;
    }

    public void setJtpInputs(JTabbedPane jtpInputs) {
        this.jtpInputs = jtpInputs;
    }

    public JTabbedPane getJtpTables() {
        return jtpTables;
    }

    public void setJtpTables(JTabbedPane jtpTables) {
        this.jtpTables = jtpTables;
    }

    public JTextField getTxtEmailPassword() {
        return txtEmailPassword;
    }

    public void setTxtEmailPassword(JTextField txtEmailPassword) {
        this.txtEmailPassword = txtEmailPassword;
    }

    public JTextField getTxtIdPassword() {
        return txtIdPassword;
    }

    public void setTxtIdPassword(JTextField txtIdPassword) {
        this.txtIdPassword = txtIdPassword;
    }

    public JTextField getTxtNotePassword() {
        return txtNotePassword;
    }

    public void setTxtNotePassword(JTextField txtNotePassword) {
        this.txtNotePassword = txtNotePassword;
    }

    public JTextField getTxtPasswordPassword() {
        return txtPasswordPassword;
    }

    public void setTxtPasswordPassword(JTextField txtPasswordPassword) {
        this.txtPasswordPassword = txtPasswordPassword;
    }

    public JTextField getTxtSearchPassword() {
        return txtSearchPassword;
    }

    public void setTxtSearchPassword(JTextField txtSearchPassword) {
        this.txtSearchPassword = txtSearchPassword;
    }

    
    
}
